<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ButterMorph\ButterMorph.csproj" />
    <ProjectReference Include="..\..\src\ButterMorph.Json\ButterMorph.Json.csproj" />
    <ProjectReference Include="..\..\src\ButterMorph.Json.Schema\ButterMorph.Json.Schema.csproj" />
    <ProjectReference Include="..\..\src\ButterMorph.Design\ButterMorph.Design.csproj" />
    <ProjectReference Include="..\..\src\ButterMorph.Web.Razor\ButterMorph.Web.Razor.csproj" />
    <ProjectReference Include="..\..\src\ButterMorph.SchemaDesign\ButterMorph.SchemaDesign.csproj" />
    <ProjectReference Include="..\..\samples\ButterMorph.Playground\ButterMorph.Playground.csproj" />
    <ProjectReference Include="..\..\samples\ButterMorph.StudioPlayground\ButterMorph.StudioPlayground.csproj" />
  </ItemGroup>
</Project>

