<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ButterMorph\ButterMorph.csproj" />
    <ProjectReference Include="..\ButterMorph.Design\ButterMorph.Design.csproj" />
    <ProjectReference Include="..\ButterMorph.Json.Schema\ButterMorph.Json.Schema.csproj" />
    <ProjectReference Include="..\ButterMorph.SchemaDesign\ButterMorph.SchemaDesign.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="wwwroot\buttermorph\designer.css" LogicalName="ButterMorph.Web.Razor.wwwroot.buttermorph.designer.css" />
    <EmbeddedResource Include="wwwroot\buttermorph\designer.js" LogicalName="ButterMorph.Web.Razor.wwwroot.buttermorph.designer.js" />
    <EmbeddedResource Include="wwwroot\buttermorph\buttermorph-host.js" LogicalName="ButterMorph.Web.Razor.wwwroot.buttermorph.buttermorph-host.js" />
    <EmbeddedResource Include="wwwroot\buttermorph\buttermorph-schema.css" LogicalName="ButterMorph.Web.Razor.wwwroot.buttermorph.buttermorph-schema.css" />
    <EmbeddedResource Include="wwwroot\buttermorph\buttermorph-schema-builder.js" LogicalName="ButterMorph.Web.Razor.wwwroot.buttermorph.buttermorph-schema-builder.js" />
    <EmbeddedResource Include="wwwroot\buttermorph\buttermorph-schema-metadata-editor.js" LogicalName="ButterMorph.Web.Razor.wwwroot.buttermorph.buttermorph-schema-metadata-editor.js" />
    <EmbeddedResource Include="wwwroot\buttermorph\buttermorph-type-version-editor.js" LogicalName="ButterMorph.Web.Razor.wwwroot.buttermorph.buttermorph-type-version-editor.js" />
    <EmbeddedResource Include="wwwroot\buttermorph\buttermorph-metadata-field-editor.js" LogicalName="ButterMorph.Web.Razor.wwwroot.buttermorph.buttermorph-metadata-field-editor.js" />
    <EmbeddedResource Include="wwwroot\buttermorph\vendor\codemirror\codemirror.min.css" LogicalName="ButterMorph.Web.Razor.wwwroot.buttermorph.vendor.codemirror.codemirror.min.css" />
    <EmbeddedResource Include="wwwroot\buttermorph\vendor\codemirror\codemirror.min.js" LogicalName="ButterMorph.Web.Razor.wwwroot.buttermorph.vendor.codemirror.codemirror.min.js" />
    <EmbeddedResource Include="wwwroot\buttermorph\vendor\codemirror\show-hint.min.css" LogicalName="ButterMorph.Web.Razor.wwwroot.buttermorph.vendor.codemirror.show-hint.min.css" />
    <EmbeddedResource Include="wwwroot\buttermorph\vendor\codemirror\show-hint.min.js" LogicalName="ButterMorph.Web.Razor.wwwroot.buttermorph.vendor.codemirror.show-hint.min.js" />
  </ItemGroup>
</Project>
