<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ButterMorph.Design\ButterMorph.Design.csproj" />
    <ProjectReference Include="..\ButterMorph.Abstractions\ButterMorph.Abstractions.csproj" />
    <ProjectReference Include="..\ButterMorph.Core\ButterMorph.Core.csproj" />
    <ProjectReference Include="..\ButterMorph.Json.Schema\ButterMorph.Json.Schema.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="wwwroot\buttermorph\designer.css" LogicalName="ButterMorph.Web.Razor.wwwroot.buttermorph.designer.css" />
    <EmbeddedResource Include="wwwroot\buttermorph\designer.js" LogicalName="ButterMorph.Web.Razor.wwwroot.buttermorph.designer.js" />
  </ItemGroup>


</Project>
